---
language: cpp
matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
      install:
        - make install_deps
        - source setup.bash
      script:
        - mkdir build && cd build
        - cmake -DPYTHON_EXECUTABLE=$(which python2) ..
        - make
        - make run_tests

    - os: osx
      compiler: clang
      install:
        - make install_deps
        - source setup.bash
      script:
        - mkdir build && cd build
        - cmake -DPYTHON_EXECUTABLE=$(which python2) ..
        - make
        - make run_tests
